name: Release
on:
  push:
    tags:
      # Rough semantic version regexp to only create releases
      # on complete semantic versions e.g. v1.0.0, but not v1.
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: crazy-max/ghaction-upx@v2
        with:
          install-only: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_BUILDKIT: 1
      - uses: ./
      - name: Run kontrol package
        run: node .github/workflows/release.js
